# Generated by Django 4.1.6 on 2023-02-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id_accesorio', models.AutoField(primary_key=True, serialize=False)),
                ('accesorio_minicargador', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'accesorio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('celular', models.CharField(blank=True, max_length=12, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.BigAutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=100)),
                ('obra', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora_ingreso', models.DateField()),
                ('hora_termino', models.DateField()),
                ('horometro_inicial', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('horometro_final', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('equipo_numero', models.CharField(max_length=50)),
                ('horas_arriendo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observaciones', models.CharField(max_length=1024)),
                ('img_maquinaria', models.BinaryField(blank=True, null=True)),
                ('img_report', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccesorioReporte',
            fields=[
                ('a_id_accesorio', models.OneToOneField(db_column='a_id_accesorio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Reportes.accesorio')),
            ],
            options={
                'db_table': 'accesorio_reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('p_id_persona', models.OneToOneField(db_column='p_id_persona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Reportes.persona')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('contraseña_usuario', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
