# Generated by Django 4.1.6 on 2023-03-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0002_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id_correo', models.BigAutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=100)),
                ('cuerpo', models.CharField(max_length=2048)),
                ('imagen', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'correo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorreoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'correo_contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEnvio',
            fields=[
                ('id_tipo', models.SmallAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_envio',
                'managed': False,
            },
        ),
    ]
