# Generated by Django 4.1.6 on 2023-06-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0003_contacto_correo_correocontacto_tipoenvio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCorreo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.FileField(null=True, upload_to='archivos_correos')),
            ],
            options={
                'db_table': 'archivo_correo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenCorreo',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes_correos')),
            ],
            options={
                'db_table': 'imagen_correo',
                'managed': False,
            },
        ),
    ]
