# Generated by Django 4.1.6 on 2023-08-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0004_archivocorreo_imagencorreo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkmaquina',
            fields=[
                ('id_check', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_1', models.BooleanField()),
                ('check_2', models.BooleanField()),
                ('check_3', models.BooleanField()),
                ('check_4', models.BooleanField()),
                ('check_5', models.BooleanField()),
                ('check_6', models.BooleanField()),
                ('check_7', models.BooleanField()),
                ('check_8', models.BooleanField()),
                ('check_9', models.BooleanField()),
                ('check_10', models.BooleanField()),
                ('check_11', models.BooleanField()),
                ('check_12', models.BooleanField()),
                ('check_13', models.BooleanField()),
                ('check_14', models.BooleanField()),
                ('check_15', models.BooleanField()),
            ],
            options={
                'db_table': 'checkmaquina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id_inspeccion', models.BigAutoField(primary_key=True, serialize=False)),
                ('inspeccion', models.CharField(max_length=100)),
                ('check1', models.CharField(max_length=50)),
                ('busqueda', models.CharField(max_length=512)),
                ('check2', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'inspeccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id_mantencion', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('numero_maquina', models.CharField(max_length=20)),
                ('horometro_maq', models.DecimalField(decimal_places=1, max_digits=10)),
                ('descripcion', models.CharField(max_length=1024)),
                ('observacion', models.CharField(max_length=1024)),
                ('insumos', models.CharField(max_length=512)),
                ('prox_mantencion', models.CharField(max_length=200)),
                ('prox_horometro', models.DecimalField(decimal_places=1, max_digits=10)),
                ('archivo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'mantencion',
                'managed': False,
            },
        ),
    ]
